apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: microservices-cert
  namespace: default
spec:
  secretName: microservices-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: microservices.local
  dnsNames:
  - microservices.local
